### ISSUE TITLE
MRDesignLabs_Unity is built for Unity 5.6.1 but HoloToolkit and official support for HoloLens is only 5.5.0

### ISSUE THREAD

**Issue by ei2kpi** [Microsoft/MRDesignLabs_Unity#16]
The official HoloLens requirements page says to install Unity 5.5.0f1 (https://developer.microsoft.com/en-us/windows/mixed-reality/install_the_tools) but MRDesignLabs_Unity only works with Unity 5.6.1.

While it works in the editor in Unity 5.6.1, building into a UWP fails with Assets\MRDesignLab\HUX\Scripts\Buttons\ButtonIconProfileTexture.cs(8,2): error CS1032: Cannot define/undefine preprocessor symbols after first token in file

Either HoloToolkit and the official recommended Unity Editor for HoloLens should be updated to Unity 5.6.x or MRDesignLabs_Unity should be downgraded to Unity 5.5.x

**Comment by paseb** [comment]
That is old data on the developer site you should always reference what's on the GitHub ReadMe.md on the HoloToolkit or MRDesignLabs front page for what's recommended from the unity editor standpoint.  We will always try to maintain MRDesignLabs to be compatible with the latest Unity editor.  I'll take a look at the ifdef and resolve the bug you're seeing.

thanks,
-pat

**Comment by ei2kpi** [comment]
Gotcha... I missed reading the ReadMe on the HoloToolkit page... apologies for that...
Do I need to use Unity 5.6.1 with VS2017 or should it work with VS2015?

Also, I tried building for 14393 and the 10586 SDKs and both hit that same issue.

When I look at the file, it does seem to be right before the namespace so not sure why that error gets thrown...

![image](https://user-images.githubusercontent.com/6269548/27462413-b51d5428-578e-11e7-93bb-f49b2567c94b.png)

**Comment by paseb** [comment]
Should be fixed now.  I got into a local state where I had to restart to nuke my temp and library directories.  The conditional defines should just wrap the individual call but the main problem was that System.Reflection was not defined aka no "using System.Reflections". Also fixed an issue with double inheritance on an abstract protected function.  Should be all good.

**Comment by ei2kpi** [comment]
Yay! You are a god Patrick!

FYI, you might want to fix the same files in the DesignLabs_Unity_Examples project as well...
